// Generated by CoffeeScript 1.6.2
var app, db;

app = process.app;

db = process.db;

if (app.get('mode') === 'development') {
  db.query("CREATE TABLE IF NOT EXISTS `videos` (	  `id` int(11) NOT NULL AUTO_INCREMENT,	  `video_code` varchar(64) NOT NULL,	  `last_played` timestamp NULL DEFAULT NULL,	  PRIMARY KEY (`id`)	) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;");
} else {
  db.query("create table if not exists videos (		id SERIAL PRIMARY KEY,		video_code varchar(40) NOT NULL,		last_played timestamp DEFAULT NULL	)");
}
