// Generated by CoffeeScript 1.6.2
(function() {
  ({
    "name": "application-name",
    "version": "0.0.1",
    "private": true,
    "scripts": {
      "start": "node app.js"
    },
    "dependencies": {
      "express": "3.2.5",
      "jade": "*"
    }
  });

}).call(this);
